# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://sarah-allec.github.io
title: Sarah Allec
email: sarah.allec@pnnl.gov
author: Sarah Allec
description: "Sarah's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/sarah-allec
  - icon: envelope-o
    title: email
    url: mailto:sarah.allec@pnnl.gov
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/sarah-allec/
  - icon: file-pdf-o
    title: CV
    url: img/sarah_allec_cv.pdf
#  - icon: website
#    title: CV Lattes
#    url: http://lattes.cnpq.br/5399100590606067
#  - icon: twitter
#   title: twitter
#    url: https://twitter.com/danicassol

